### ISSUE TITLE
PHP Error:  Class 'LightningSale/LndClient/ClientFactory' not found

### ISSUE THREAD

**Issue by MattThurling** [lightningsale/lnd-rest-php#7]
Hi

Not sure if this is an issue with this package but thought I'd ask here first. I've set up a Lightning node on a Raspberry Pi and then wanted to run a Laravel application using your client to interface. I am a bit of a noob to all of this and seem to have got stuck.

I have a development environment using Ubuntu on Homestead on a mac and everything works fine - I can access the class create a client - but on the Raspberry Pi (running Raspian Stretch) I keep getting:

PHP Error:  Class 'LightningSale/LndClient/ClientFactory' not found

no matter how I try to access the class. Like I say, it works on one environment and not the other. Unfortunately, the Raspberry Pi is where the Bitcoin node is running.

Probably more likely to be something extremely stupid I am doing but was just wondering if there were any quirks in Psr with how this package registers itself via composer...?

**Comment by Richard87** [comment]
Hi!

Did you use `composer require lightningsale/lnd-client` to install it, or some other way?

Did you load Composers autoloader?

```php
<?php

require './vendor/autoload.php';

$client = LightningSale/LndClient/ClientFactory::createRestClient("hostname", "port", "tls.cert", "admin.macaroon", new Psr\Log\NullLogger());

var_dump($client->getInfo());
```

It would be way easier to help you if I could see the code you are using :)


## Edit!
I need to be better at reading the whole message!

Did you run "composer install" after updating the code on the raspberry pi to install any missing dependencies (like LndClient), or you could try `composer dump-autoload` to update the autoloader :)

**Comment by MattThurling** [comment]
Hi - and thanks for getting back to me.  I have just figured out what the problem is. I'd not been able to upgrade the Pi to PHP 7.1 so it's running 7.0. Your version 0.4.1 requires it so composer was falling back and installing your 0.2.0.

**Comment by Richard87** [comment]
Ahh, good you spotted the problem! Good luck on upgrading to 7.2 / 7.1 :)


Richard

**Comment by MattThurling** [comment]
Thanks. I'll give that a try tonight. Out of interest, what is it in your code that requires 7.1 (just curious as am pretty new to this)

**Comment by Richard87** [comment]
No problem!

Scalar type-hints, so that each method can tell you that it requires a int
or string, this removes a few types of bugs that can occure, and I prefer
beeing as strict as possible when working with money! :)


Richard

tor. 19. apr. 2018 kl. 09:40 skrev MattThurling <notifications@github.com>:

**Comment by MattThurling** [comment]
Cool. Yes, I noticed that in the code and had to look it up! Isn't it just a 7.0 thing though, or was there more added for 7.1?

Great project, btw. I just found the client initially but just had a look at the whole POS app. Awesome! Are you on it full time?

**Comment by Richard87** [comment]
Hi, no unfortunatley, I have a dayjob as well that takes up most of my
time...

Yeah, you are right, type hinting doesn't require PHP 7.1...

I took a second look and found out the only things I'm using is *shorthang
unpacking:*
[image: image.png]

Og *void og nullable* return types...


Richard

tor. 19. apr. 2018 kl. 10:27 skrev MattThurling <notifications@github.com>:

**Comment by MattThurling** [comment]
Hmm, doesn't seem possible to install 7.1 on Pi. It has dependencies that are 'not installable'. Shame, I think there are quite a few people experimenting with Lightning on Pis at this point in time (hint, hint) :)

**Comment by Richard87** [comment]
which dependencies are that?

Could you try to use pecl? "pecl install extension"?

fre. 20. apr. 2018 kl. 09:25 skrev MattThurling <notifications@github.com>:

**Comment by MattThurling** [comment]
Seems like it's pretty fundamental stuff:

The following packages have unmet dependencies:
 php7.1 : Depends: libapache2-mod-php7.1 but it is not installable or
                   php7.1-fpm but it is not installable or
                   php7.1-cgi but it is not installable
          Depends: php7.1-common but it is not installable
E: Unable to correct problems, you have held broken packages.

I think it might be to do with the hardware (arm64) not being supported

**Comment by Richard87** [comment]
Yeah, PHP7.2 is missing in the default repositories... You must add the stretch repo to be able to update to the current version...

But, I am running LightningSale in Docker, is that a solution that could work for you? I'm not sure how arm64 works with Docker tho...

**Comment by MattThurling** [comment]
Yeah, I'm not sure. TBH I am amazed I managed to get as far as I did with the Pi and fear that if I start experimenting with obscure repos it will all come apart.  All I really wanted to do was make a test transaction to my node via web interface so I will just take a look at what you've done with Guzzle and see if I can recreate it.
I think you tried to send a pic of the 7.1 specific code you were using but your Tor client filtered out the png...? Be interested to know what that was and whether it's in the client or in the larger POS.

**Comment by Richard87** [comment]
Ahh, it should be easy to make it work on 7.1:

- use list() for unpacking arrays, change `[$a, $b]  = [1,2]` to `list($a, $b) = [1,2]`
- remove all `void` return variables
- remove all `nullable` return variables, change `function a(): ?Something {...}` to `function a() {...}`

**Comment by MattThurling** [comment]
Thanks so much. Awesome.  I'm actually stuck with 7.0 for now but will see how it goes with those changes.
